name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Submit Cloud Build
        id: build
        run: |
          BUILD_ID=$(gcloud builds submit --config cloudbuild.yaml --async --format="value(id)" .)
          echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
          echo "✅ Cloud Build submitted: $BUILD_ID"
          echo "🔗 Logs: https://console.cloud.google.com/cloud-build/builds/$BUILD_ID"

      - name: Wait for Build Completion
        run: |
          BUILD_ID=${{ steps.build.outputs.build_id }}
          echo "⏳ Waiting for build $BUILD_ID to complete..."
          for i in {1..60}; do
            STATUS=$(gcloud builds describe $BUILD_ID --format="value(status)" 2>/dev/null || echo "QUEUED")
            echo "Status: $STATUS"
            if [ "$STATUS" = "SUCCESS" ]; then
              echo "✅ Build completed successfully!"
              exit 0
            elif [ "$STATUS" = "FAILURE" ] || [ "$STATUS" = "TIMEOUT" ] || [ "$STATUS" = "CANCELLED" ]; then
              echo "❌ Build failed: $STATUS"
              echo "🔗 Check logs: https://console.cloud.google.com/cloud-build/builds/$BUILD_ID"
              exit 1
            fi
            sleep 10
          done
          echo "⚠️ Build timeout after 10 minutes"
          exit 1

